package integrations

import "github.com/idcu/ngm/internal/mappings"

// EsbuildScriptPath 是 esbuild 的构建脚本。
//
// esbuild 没有约定俗成的配置文件，因此生成一个**可执行的脚本**：
// `node ngm.esbuild.cjs`。文件名属于 ngm（`ngm.*`），可以随依赖变化重生成。
//
// 用 CommonJS 而不是 ESM（`.mjs`）：ESM 的模块解析**不认 NODE_PATH**，
// 因此 esbuild 必须装在项目里才 import 得到；`require` 则同时接受项目内安装与
// 全局安装（`npm i -g esbuild`）。这是实测出来的差别：
// `node ngm.esbuild.mjs` 在只有全局 esbuild 时报 ERR_MODULE_NOT_FOUND。
const EsbuildScriptPath = "ngm.esbuild.cjs"

func esbuildArtifacts(f *mappings.File) ([]Artifact, []string) {
	return []Artifact{{
		Path:    EsbuildScriptPath,
		Content: []byte(esbuildScript),
		Owned:   true,
		Purpose: "esbuild: alias read from ngm.mappings.json, runnable with `node " + EsbuildScriptPath + "`",
	}}, nil
}

// esbuildScript 导出 alias 供用户合并进自己的构建脚本，同时在**直接执行**时构建一次。
//
// "直接执行才构建"这个判断不是洁癖：没有它，任何人 `require('./ngm.esbuild.cjs')`
// 都会触发一次构建——一个配置文件不该在被读取时产生副作用。
const esbuildScript = `// Generated by "ngm integrations add esbuild". ngm owns this file and rewrites
// it on the next run; put your own settings in a separate build script.
const { build } = require('esbuild')
const { readFileSync } = require('node:fs')
const { join } = require('node:path')

const mappings = JSON.parse(readFileSync(join(__dirname, 'ngm.mappings.json'), 'utf8'))

// The import specifier is not just "from": a monorepo dependency can appear
// under several subpaths, and they all share the same "from".
const specifier = (m) => (m.path ? m.from + '/' + m.path : m.from)

// Point at the entry file, not the directory: a directory only resolves when it
// happens to contain index.*, while "main" may well be ./src/main.ts.
const entry = (m) => {
  const to = m.to.replace(/\/+$/, '')
  return m.main ? to + '/' + m.main.replace(/^\.?\//, '') : to
}

const alias = Object.fromEntries(
  // Longest key first is defensive: esbuild picks the most specific match on its
  // own (measured - the order of the aliases does not change the result), but
  // ordering them this way is harmless and reads better.
  mappings.mappings
    .slice()
    .sort((a, b) => specifier(b).length - specifier(a).length)
    .map((m) => [specifier(m), entry(m)]),
)

module.exports = { alias }

// Only build when run directly (node ngm.esbuild.cjs), never on require.
if (require.main === module) {
  build({
    entryPoints: ['src/index.ts'],
    outfile: 'dist/index.js',
    bundle: true,
    alias,
  }).catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
`
