package integrations

import "github.com/idcu/ngm/internal/mappings"

// ViteConfigPath 是 Vite 的配置文件（用户可能已有，因此永不覆盖）。
const ViteConfigPath = "vite.config.ts"

func viteArtifacts(f *mappings.File) ([]Artifact, []string) {
	return []Artifact{{
		Path:    ViteConfigPath,
		Content: []byte(viteConfig),
		Purpose: "Vite: resolve.alias, read from ngm.mappings.json at build time",
	}}, nil
}

// viteConfig 在**构建时读取** mappings：依赖增删后不需要重新生成配置。
//
// 生成的文件里重复了 specifier / 排序逻辑（而不是把结果内联进来）是刻意的：
// 内联会让配置在每次依赖变化后过期，而"配置过期"这类问题最难被发现——
// 构建仍然成功，只是解析到了旧路径。
const viteConfig = `// Generated by "ngm integrations add vite".
//
// The aliases are read from ngm.mappings.json when Vite starts, so adding or
// removing a dependency does not require regenerating this file.
import { defineConfig } from 'vite'
import mappings from './ngm.mappings.json'

type Mapping = { from: string; path?: string; to: string; main?: string }

// The import specifier is not just "from": a monorepo dependency can appear
// under several subpaths, and they all share the same "from".
const specifier = (m: Mapping) => (m.path ? m.from + '/' + m.path : m.from)

// Point at the entry file, not the directory: a directory only resolves when it
// happens to contain index.*, while "main" may well be ./src/main.ts.
const entry = (m: Mapping) => {
  const to = m.to.replace(/\/+$/, '')
  return m.main ? to + '/' + m.main.replace(/^\.?\//, '') : to
}

export default defineConfig({
  resolve: {
    alias: (mappings.mappings as Mapping[])
      // Longest key first is defensive: it is harmless where the tool sorts
      // matches itself, and safer where that has not been verified.
      .slice()
      .sort((a, b) => specifier(b).length - specifier(a).length)
      .map((m) => ({ find: specifier(m), replacement: entry(m) })),
  },
})
`
