package integrations

import "github.com/idcu/ngm/internal/mappings"

// WebpackConfigPath 是生成的 Webpack 配置。
const WebpackConfigPath = "ngm.webpack.cjs"

func webpackArtifacts(f *mappings.File) ([]Artifact, []string) {
	return []Artifact{{
		Path:    WebpackConfigPath,
		Content: []byte(webpackConfig),
		Owned:   true,
		Purpose: "Webpack: resolve.alias read from ngm.mappings.json",
	}}, nil
}

// webpackConfig 用 CommonJS：Webpack 配置在 `.cjs` 下不受宿主 package.json 的
// `type: module` 影响，少一类"同一份配置在不同项目里行为不同"的问题。
//
// 每个键都带 `$` 后缀：Webpack 的别名默认也是**前缀**匹配，
// `$` 才表示精确匹配。没有它，`github:org/repo` 会吞掉 `github:org/repo/packages/core`。
const webpackConfig = `// Generated by "ngm integrations add webpack". ngm owns this file and rewrites
// it on the next run; merge the alias map into your own config if you have one.
const { readFileSync } = require('node:fs')
const { join, resolve } = require('node:path')

const mappings = JSON.parse(readFileSync(join(__dirname, 'ngm.mappings.json'), 'utf8'))

// The import specifier is not just "from": a monorepo dependency can appear
// under several subpaths, and they all share the same "from".
const specifier = (m) => (m.path ? m.from + '/' + m.path : m.from)

// Point at the entry file, not the directory: a directory only resolves when it
// happens to contain index.*, while "main" may well be ./src/main.ts.
const entry = (m) => {
  const to = resolve(__dirname, m.to.replace(/^\.\//, '').replace(/\/+$/, ''))
  return m.main ? join(to, m.main.replace(/^\.?\//, '')) : to
}

// The trailing $ forces an exact match. Webpack prefix-matches by default, and
// an exact key is the one behaviour that does not depend on which of two
// matching aliases the tool prefers.
const alias = Object.fromEntries(
  mappings.mappings
    .slice()
    .sort((a, b) => specifier(b).length - specifier(a).length)
    .map((m) => [specifier(m) + '$', entry(m)]),
)

module.exports = { resolve: { alias } }
`
